package com.ifountain.rcmdb.domain.generation

import com.ifountain.rcmdb.domain.operation.AbstractDomainOperation

/**
* Created by IntelliJ IDEA.
* User: Administrator
* Date: Jun 23, 2008
* Time: 9:44:51 AM
* To change this template use File | Settings | File Templates.
*/
class ModelGenerationUtils {
    
    public static String generateClassText(File classFile, String className, String parentClassName, String autoGeneratedCode, List defaultImports)
    {
        def classContent = ClassParser.parseClass(classFile);
        def generatedClassContent = new ClassContent();
        def imports = classContent.getLines(ClassContentLine.IMPORT_LINE);
        def parentClass = classContent.getParentClass()
        def implementedClasses = classContent.getImplementedClasses()
        boolean isClassDeclerationProcessed = false;
        classContent.lines.each{ClassContentLine line->
            if(!isClassDeclerationProcessed && line.type == ClassContentLine.CLASS_DECLERATION_LINE)
            {
                isClassDeclerationProcessed = true;
                defaultImports.each {defaultImport->
                    def found = false;
                    def firstImport
                    imports.each{ClassContentLine importLine->
                        if(importLine.line.indexOf(defaultImport) >= 0)
                        {
                            found = true;
                        }
                    }
                    if(!found)
                    {
                        generatedClassContent.addLine("import ${defaultImport};", ClassContentLine.IMPORT_LINE);
                    }
                }
                def declerationLine = "class ${className} "
                if(parentClassName)
                {
                    declerationLine += " extends ${parentClassName} ";
                }
                if(implementedClasses.size() != 0)
                {
                    declerationLine += "implements ${implementedClasses[0]}"
                    for(int i= 1; i < implementedClasses.size(); i++)
                    {
                        declerationLine += ", ${implementedClasses[i]}"
                    }
                }
                generatedClassContent.addLine (declerationLine + "{", ClassContentLine.CLASS_DECLERATION_LINE);
                if(autoGeneratedCode != ""){
                    generatedClassContent.addLine (autoGeneratedCode, ClassContentLine.AUTO_GENERATED_LINE);
                }
            }
            if(line.type != ClassContentLine.AUTO_GENERATED_LINE && line.type != ClassContentLine.CLASS_DECLERATION_LINE && line.type != ClassContentLine.PACKAGE_DECLERATION_LINE )
            {
                generatedClassContent.addLine(line.line, line.type);
            }
        }
        return generatedClassContent.toString();
    }
}